### ISSUE TITLE
No debug constants check in legacy controller

### ISSUE THREAD

**Issue by peterwimmer** [friteuseb/semantic_suggestion#10]
It seems, that in the V12 controller there is no check for the debug typoscript setting and the log entries are always written to the log in typo3temp.

https://github.com/friteuseb/semantic_suggestion/blob/4a6cf0fd7c8f0b9952cf2b21beca07070b04b85e/Classes/Controller/LegacySemanticBackendController.php#L51

Thank you for your extension, we are starting to test it and learn about all the possibilities.

**Comment by friteuseb** [comment]
The issue has been fixed in the upcoming commit. The
  `logDebug()` method now checks the `debugMode` setting before
   writing logs.

  ## Changes made
  In `Classes/Controller/LegacySemanticBackendController.php`
  (lines 49-58), the method now checks the configuration:
  ```php
  private function logDebug(string $message, array $context =
  []): void
  {
      // Retrieve settings from PageAnalysisService
      $settings = $this->pageAnalysisService->getSettings();

      // Check if debugMode is enabled before writing logs
      if (isset($settings['debugMode']) &&
  $settings['debugMode']) {
          $this->logger->debug($message, $context);
      }
  }

  Logs will now only be written if
  plugin.tx_semanticsuggestion_suggestions.settings.debugMode =
   1 is set in the TypoScript configuration.

  @peterwimmer Could you please test this fix to confirm it
  works as expected?

**Comment by peterwimmer** [comment]
@friteuseb Hello Cyril, thanks for this fix. This works as expected.

In my checks i still get some debug logs and these are from the "SiteLanguageService.php" class.  Perhaps this is the same cause? The log looks like this:

Tue, 30 Sep 2025 15:53:47 +0200 [DEBUG] request="0da7b7c100a3b" component="TalanHdf.SemanticSuggestion.Service.SiteLanguageService": Language detected from TYPO3 site config - {"pageId":8523,"
languageUid":0,"detectedCode":"de"}

**Comment by friteuseb** [comment]
Thanks for reporting !  I've fixed it by updating the logDebug method in
LegacySemanticBackendController.php to check TYPO3's global debug setting
($GLOBALS['TYPO3_CONF_VARS']['SYS']['debug']) instead of the extension's
debugMode setting. This ensures debug logs are only written when TYPO3 debug mode
is enabled. The fix has been committed in 1574c38
https://github.com/friteuseb/semantic_suggestion/commit/1574c38.
